swagger: '2.0'
info:
  title: Transaction Management API
  description: This API allows users to manage their banking transactions, including retrieving, adding, modifying and deleting transactions.
  version: 2.0.0
host: localhost:3001
basePath: /api/v2
schemes:
  - http
paths:
  /user/transactions:
    get:
      tags:
          - Transactions
      summary:  all transactions for current month
      description: API for fetching current month transactions
      parameters:
        - name: Authorization
          in: header
          required: true
          description: Attach Bearer JWT token
          type: string
      responses:
                "200":
                    description: User transactions retrieved successfully
                "400":
                    description: Invalid Fields
                "401":
                    description: Unauthorized
                "404":
                    description: Transactions not found
                "500":
                    description: Internal Server Error
  /user/transactions/{id}:
    get:
      tags:
          - Transactions
      summary: details of a transaction
      description: API to show a transaction
      parameters:
          - in: header
            name: Authorization
            description: Attach Bearer JWT token
            required: true
            type: string
          - in: path
            name: id
            description: Id of the transaction
            required: true
            type: string
      responses:
              "200":
                  description: transaction retrieved successfully
              "400":
                  description: Invalid Field
              "401":
                  description: Unauthorized
              "404":
                  description: Transactions not found
              "500":
                  description: Internal Server Error
    patch:
      tags:
          - Transactions
      summary: modify transaction information
      description: API to modify a transaction
      parameters:
      responses:
              "200":
                  description: transaction patched successfully
              "400":
                  description: Invalid Fields
              "401":
                  description: Unauthorized
              "404":
                  description: Transactions not found
              "500":
                  description: Internal Server Error
    post:
      tags:
          - Transactions
      summary: add transaction information
      description: API to add a transaction
      parameters:
      responses:
              "200":
                  description: transaction post successfully
              "400":
                  description: Invalid Fields
              "401":
                  description: Unauthorized
              "404":
                  description: Transactions not found
              "500":
                  description: Internal Server Error
    delete:
      tags:
          - Transactions
      summary: delete transaction information
      description: API to delete a transaction
      parameters:
      responses:
              "200":
                 description: transaction delete successfully
              "400":
                 description: Invalid Fields
              "401":
                  description: Unauthorized
              "404":
                  description: Transactions not found
              "500":
                  description: Internal Server Error
    